---------------------drop seq--------------------------------------
drop sequence fact_closed_crimes_seq;
drop sequence dim_location_seq;
drop sequence dim_crime_type_seq;
drop sequence dim_time_seq;
drop sequence dim_police_officer_seq;

--------------------------drop trig------------------------------
drop trigger fact_closed_crimes_trig;
drop trigger dim_location_trig;
drop trigger dim_crime_type_trig;
drop trigger dim_time_trig;
drop trigger dim_police_officer_trig;


-----------------drop tables---------------------------------------
DROP TABLE 	fact_closed_crimes  CASCADE CONSTRAINTS;
DROP TABLE 	dim_location  CASCADE CONSTRAINTS;
DROP TABLE 	dim_crime_type  CASCADE CONSTRAINTS;
DROP TABLE 	dim_time  CASCADE CONSTRAINTS;
DROP TABLE 	dim_police_officer  CASCADE CONSTRAINTS;


---------------------------create SEQ------------------------
create sequence fact_closed_crimes_seq start with 1 increment by 1;
create sequence dim_location_seq start with 1 increment by 1;
create sequence dim_crime_type_seq start with 1 increment by 1;
create sequence dim_time_seq start with 1 increment by 1;
create sequence dim_police_officer_seq start with 1 increment by 1;


--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Verbose generation: ON

-- note: spaces within table/column names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- To drop the tables generated by this script run -
--   'C:\Users\mohan\Desktop\L6\ADS\assessment1\hdhdhd_drop.sql'

--------------------------------------------------------------



--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.

-- Create a Database table to represent the "fact_closed_crimes" entity.
CREATE TABLE fact_closed_crimes(
	crime_key	INTEGER NOT NULL,
	time_id	INTEGER NOT NULL,
	location_id	INTEGER NOT NULL,
	crimetype_id	INTEGER NOT NULL,
	officer_id	INTEGER NOT NULL,
	no_of_crimes	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "fact_closed_crimes".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_fact_closed_crimes PRIMARY KEY (crime_key)
);

-- Create a Database table to represent the "dim_time" entity.
CREATE TABLE dim_time(
	time_id	INTEGER NOT NULL,
	year	VARCHAR(8),
	month	VARCHAR(8),
	day	VARCHAR(8),
	-- data_source	VARCHAR(40),
	-- Specify the PRIMARY KEY constraint for table "dim_time".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_dim_time PRIMARY KEY (time_id)
);

-- Create a Database table to represent the "dim_location" entity.
CREATE TABLE dim_location(
	location_id	INTEGER NOT NULL,
	location_key	INTEGER,
	region_name	VARCHAR(20),
	street_name	VARCHAR(20),
	post_code	VARCHAR(20),
	city_name	VARCHAR(20),
	data_source	VARCHAR(40),
	-- Specify the PRIMARY KEY constraint for table "dim_location".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_dim_location PRIMARY KEY (location_id)
);

-- Create a Database table to represent the "dim_crime_type" entity.
CREATE TABLE dim_crime_type(
	crimetype_id	INTEGER NOT NULL,
	crime_type_key	INTEGER,
	closure_status	VARCHAR(20),
	crime_type	VARCHAR(40),
	data_source	VARCHAR(40),
	-- Specify the PRIMARY KEY constraint for table "dim_crime_type".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_dim_crime_type PRIMARY KEY (crimetype_id)
);

-- Create a Database table to represent the "dim_police_officer" entity.
CREATE TABLE dim_police_officer(
	officer_id	INTEGER NOT NULL,
	police_officer_key	INTEGER,
	full_name	VARCHAR(40),
	department	VARCHAR(20),
	rank	INTEGER,
	data_source	VARCHAR(40),
	-- Specify the PRIMARY KEY constraint for table "dim_police_officer".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_dim_police_officer PRIMARY KEY (officer_id)
);


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "fact_closed_crimes_dim_time" relationship

-- This constraint ensures that the foreign key of table "fact_closed_crimes"
-- correctly references the primary key of table "dim_time"

ALTER TABLE fact_closed_crimes ADD CONSTRAINT fk1_cc_to_dt FOREIGN KEY(time_id) REFERENCES dim_time(time_id);

-- Alter table to add new constraints required to implement the "fact_closed_crimes_dim_location" relationship

-- This constraint ensures that the foreign key of table "fact_closed_crimes"
-- correctly references the primary key of table "dim_location"

ALTER TABLE fact_closed_crimes ADD CONSTRAINT fk2_cc_to_dl FOREIGN KEY(location_id) REFERENCES dim_location(location_id);

-- Alter table to add new constraints required to implement the "fact_closed_crimes_dim_crime_type" relationship

-- This constraint ensures that the foreign key of table "fact_closed_crimes"
-- correctly references the primary key of table "dim_crime_type"

ALTER TABLE fact_closed_crimes ADD CONSTRAINT fk3_cc_to_ct FOREIGN KEY(crimetype_id) REFERENCES dim_crime_type(crimetype_id);

-- Alter table to add new constraints required to implement the "fact_closed_crimes_dim_police_officer" relationship

-- This constraint ensures that the foreign key of table "fact_closed_crimes"
-- correctly references the primary key of table "dim_police_officer"

ALTER TABLE fact_closed_crimes ADD CONSTRAINT fk4_cc_to_po FOREIGN KEY(officer_id) REFERENCES dim_police_officer(officer_id);


--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------


------------------- triggers for uniques id's---------------------
create or replace trigger fact_closed_crimes_trig
before insert on fact_closed_crimes
for each row
begin 
	if :NEW.crime_key is null then
		select fact_closed_crimes_seq.nextval into :new.crime_key from SYS.DUAL;
	end if;
end;
/

create or replace trigger dim_crime_type_trig
before insert on dim_crime_type
for each row
begin
	if :new.crimetype_id is null then
		select dim_crime_type_seq.nextval into :new.crimetype_id from SYS.DUAL;
	end if;
end;
/

create or replace trigger dim_time_trig
before insert on dim_time
for each row
begin
	if :new.time_id is null then
		select dim_time_seq.nextval into :new.time_id from SYS.DUAL;
	end if;
end;
/

create or replace trigger dim_location_trig
before insert on dim_location
for each row
begin
	if :new.location_id is null then
		select dim_location_seq.nextval into :new.location_id from SYS.DUAL;
	end if;
end;
/

create or replace trigger dim_police_officer_trig
before insert on dim_police_officer
for each row
begin
	if :new.officer_id is null then
		select dim_police_officer_seq.nextval into :new.officer_id from SYS.DUAL;
	end if;
end;
/